[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/opensky-auth/*"
  to = "/.netlify/functions/opensky-auth"
  status = 200

[[redirects]]
  from = "/opensky-api/*"
  to = "/.netlify/functions/opensky-api"
  status = 200

[[redirects]]
  from = "/aviationstack/*"
  to = "/.netlify/functions/aviation"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://*; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://* blob:; connect-src 'self' https://* http://*;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
